# -*- coding: utf-8 -*-

NUMERICAL_TYPE = "num"
NUMERICAL_TYPE_MAIN = "num_org"
CATEGORY_TYPE = "cat"
TEXT_TYPE = "text"
TIME_TYPE = "time"
KEY_TYPE = "key"

TEXTJA_TYPE = "textja"
SUM_CATEGORY_TYPE = "sumcat_"

OBJ_TYPE = "obj"

INFO_STRUCT = "struct"
TRAIN_MAIN_TBL = "main"
APPLY_MAIN_TBL = "apply"

NUM_ORG = "org"
NUM_MAX = "max"
NUM_MIN = "min"
NUM_AVG = "avg"
NUM_SUM = "sum"
NUM_LEN = "len"
NUM_FEATURES = {NUM_MAX: 0, NUM_MIN: 1, NUM_SUM:2, NUM_AVG: 3, NUM_LEN: 4}
NUM_FEATURES_LEN = 5

COL_NUM_ORG = 0
COL_NUM_MAX = 0
COL_NUM_MIN = 1
COL_NUM_SUM = 2
COL_NUM_AVG = 3
COL_NUM_LEN = 4

CATEGORY_NULL = "N/A"
TEXT_DELIMITER = " "
UNKNOWN_KEY = "%UNKNOWN%"

DATA_KEY_COL = "key"
DATA_KEYTIME_COL = "keytime"